<?php
/**
 * @var callable|object $v
 * @var $metaTitlePrefix
 * @var $metaTitle
 * @var $metaTitleSuffix
 * @var $appName
 * @var $userIdentity
 */
?>
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
<!--    <meta name="csrf-token" content="--><?php //echo $v->e($csrfToken); ?><!--">-->
    <title><?php echo $v("$metaTitlePrefix$metaTitle$metaTitleSuffix") ?></title>
</head>
<body>
<h1>Hello, <?php echo $v($userIdentity) ?>!</h1>
</body>
</html>
