<?php
/**
 * @var string $metaTitle
 */
?>
<?php $v->layout('Rosem/Kernel/View/layouts/base', [
    'metaTitle' => $v($metaTitle),
]) ?>

<?php $v->push('styles') ?>
<link rel="stylesheet" href="<?php echo '/css/admin.css' ?>">
<?php $v->end() ?>

<?php $v->unshift('scripts') ?>
<script src="<?php echo '/js/admin.js' ?>"></script>
<?php $v->end() ?>

<?php $v->push('body') ?>
<div id="app">Hello from admin</div>
<?php $v->end() ?>
