<?php
/**
 * @var string $metaTitlePrefix
 * @var string $metaTitle
 * @var string $metaTitleSuffix
 */
?>
<?php $v->layout('Rosem/Kernel/View/layouts/base', [
    'metaTitlePrefix' => $v($metaTitlePrefix ?? ''),
    'metaTitle'       => $v($metaTitle),
    'metaTitleSuffix' => $v($metaTitleSuffix ?? ''),
]) ?>

<?php $v->push('styles') ?>
<link rel="stylesheet" id="admin-styles">
<?php $v->end() ?>

<?php $v->unshift('scripts') ?>
<script type="text/javascript" id="admin-scripts"></script>
<?php $v->end() ?>

<?php $v->push('body') ?>
<div id="app">Hello from admin</div>
<?php $v->end() ?>
