<?php
/**
 * @var object|Closure $v
 * @var string $appName
 * @var string $appEnv
 * @var string $lang
 * @var string $metaTitlePrefix
 * @var string $metaTitle
 * @var string $metaTitleSuffix
 * @var array $polyfills
 */

use Rosem\App\AppEnvironment;

$config = [
    'appName' => $appName,
    'locale' => $lang,
];
?>
<!DOCTYPE html>
<html lang="<?php echo $v($lang ?? 'en-US') ?>">
<head>
    <meta charset="<?php echo $v($charset ?? 'utf-8') ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <title><?php echo $v($metaTitlePrefix . $metaTitle . $metaTitleSuffix) ?></title>
    <link rel="stylesheet" href="<?php echo '/css/rosem.css' ?>">
    <!--Custom styles-->
    <?php echo $v->section('styles') ?>
    <!--Polyfill JS features via polyfill.io-->
    <script defer
            src="https://cdn.polyfill.io/v2/polyfill<?php
                echo $appEnv === AppEnvironment::DEVELOPMENT ? '' : '.min'
            ?>.js?features=<?php echo implode(',', $polyfills) ?>"
    ></script>
    <!--The bundle of vendor packages-->
    <script defer src="<?php echo '/js/vendor.bundle.js' ?>"></script>
    <!--Custom scripts-->
    <?php echo $v->section('scripts') ?>
</head>
<body>
<?php echo $v->section('body') ?>
<!--Global configuration object-->
<script>window.config = <?php echo json_encode($config) ?>;</script>
<noscript>
    <p>To use <mark><?php echo $v($appName) ?></mark>, please enable JavaScript.</p>
</noscript>
<?php echo $v->section('body_end_scripts') ?>
</body>
</html>
