<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>404 Not found</title>
    <style>
    body {
        font-family: sans-serif;
        text-align: center;
        display: flex;
        flex-direction: column;
        justify-content: center;
        margin: 0;
        min-height: 100vh;
        background-color: #fafafa;
    }

    main {
        max-width: 800px;
        margin: 0 auto;
        padding: 2rem;
    }

    h1 {
        font-size: 3rem;
        font-weight: normal;
        text-align: center;
        margin: 0;
    }

    code {
        font-size: 10rem;
        font-weight: bold;
        display: block;
    }

    p {
        color: #888;
    }
    </style>
</head>
<body>
<main>
    <h1><code>404</code> Page not found</h1>
    <p>The requested URI <?php echo $v($_SERVER['REQUEST_URI']) ?? '' ?> was not found on this server.</p>
</main>
</body>
</html>
