<?php
/**
 * @var callable|object $v
 * @var $metaTitlePrefix
 * @var $metaTitle
 * @var $metaTitleSuffix
 * @var $appName
 */
?>
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Internal server error</title>
</head>
<body>
<h1>500 Internal server error</h1>
<p>The server encountered an internal error or misconfiduration and was unable to complete your request.</p>
</body>
</html>
