<?php
/**
 * @var object|Closure $v
 * @var string $metaTitle
 */
?>
<?php $v->layout('Rosem\Kernel::layouts/base', [
    'metaTitle' => $v($metaTitle),
]) ?>

<?php $v->push('styles') ?>
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat+Alternates:100,200,300,400,500,600,700">
<link rel="stylesheet" href="<?php echo '/css/admin.css' ?>">
<?php $v->end() ?>

<?php $v->push('scripts') ?>
<script defer src="<?php echo '/js/admin.js' ?>"></script>
<?php $v->end() ?>

<?php $v->start('body') ?>
<div id="app">Admin</div>
<?php $v->end() ?>
