<?php
/**
 * @var string $metaTitle
 */
?>
<?php $v->layout('Rosem.Kernel::layouts/base', [
    'metaTitle' => $v($metaTitle),
]) ?>

<?php $v->push('styles') ?>
<link rel="stylesheet" href="<?php echo '/css/site.css' ?>">
<?php $v->end() ?>

<?php $v->push('scripts'); ?>
<script src="<?php echo '/js/site.js' ?>"></script>
<?php $v->end(); ?>

<?php $v->start('body') ?>
<div id="app">Start home</div>
<?php $v->end() ?>
